sudo: required

services:
  - docker

before_install:
- docker pull rafazzevedo/bug-free-garbanzo-cypress:latest

script:
- docker run --name=bug-free-garbanzo-cypress rafazzevedo/bug-free-garbanzo-cypress:latest

after_script:
  - docker cp bug-free-garbanzo-cypress:home/garbanzo/target target/
  - docker cp bug-free-garbanzo-cypress:home/garbanzo/cypress/videos target/videos
  
addons:
  artifacts: 
    working_dir: target
